const fs = require('node:fs');
const path = require('node:path');
const read = name => fs.readFileSync(path.join(__dirname,name),'utf8');
const escape = text => text.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const blocks=[
 ['Head code','head.html','Replace the previous billing CSS and Bouncy Tabs CSS with this entire block.'],
 ['Footer code','footer.html','Replace both old JavaScript blocks with this entire block. Keep your existing GSAP include above it.'],
 ['Billing HTML — unchanged','toggle.html','Only needed if you have not already added the two-button billing control.']
].map(([title,file,description],i)=>`<section><div class="section-top"><h2>${i+1}. ${title}</h2><button type="button" data-copy="code-${i}">Copy complete code</button></div><p>${description}</p><textarea id="code-${i}" aria-label="${title}" readonly spellcheck="false">${escape(read(file))}</textarea></section>`).join('');
fs.writeFileSync(path.join(__dirname,'INSTALL.html'),`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Install Billing + Bouncy Tabs in Webflow</title><style>
*{box-sizing:border-box}body{margin:0;padding:44px 24px;background:#f4f1eb;color:#263d30;font:16px/1.6 Arial,sans-serif}main{max-width:1000px;margin:auto}h1{font-size:clamp(32px,5vw,48px);line-height:1.1;letter-spacing:-.04em}h2{font-size:22px;line-height:1.3}p{max-width:780px}.intro{font-size:18px;color:#54665a}.steps,section{padding:24px;background:#fffdf8;border:1px solid #d8dfd6;border-radius:16px;margin:22px 0}.steps li{margin:12px 0}.section-top{display:flex;align-items:center;justify-content:space-between;gap:18px}button{background:#304f3c;color:#fff;padding:12px 16px;border:0;border-radius:8px;font:inherit;cursor:pointer}button:focus-visible,textarea:focus-visible{outline:3px solid #709979;outline-offset:3px}textarea{width:100%;height:300px;padding:18px;background:#f5f7f2;color:#253c2f;border:1px solid #d4ddd0;border-radius:8px;font:13px/1.6 Consolas,monospace;resize:vertical;white-space:pre}a{color:#275a3d}code{background:#e8ede4;padding:2px 5px;border-radius:3px}#copy-status{min-height:24px}@media(max-width:600px){body{padding:24px 14px}.section-top{align-items:flex-start;flex-direction:column}section,.steps{padding:18px}}
</style></head><body><main><h1>Billing + Bouncy Tabs</h1><p class="intro">One combined package. Existing billing controls and tabs keep their behavior and attributes.</p>
<div class="steps"><ol><li><strong>Replace the old CSS</strong> with Head code below.</li><li><strong>Replace the old JavaScript</strong> with Footer code below. Keep GSAP loaded once, before this code.</li><li><strong>Keep your existing markup.</strong> No new required attributes. To preserve the old class-based text stagger, put <code>data-bouncy-tabs-item="children"</code> on the text wrapper and <code>data-bouncy-tabs-item="true"</code> on the visual.</li><li><strong>Publish to staging</strong> and check both controls.</li></ol><p><a href="SETUP.md">Complete setup guide</a> · <a href="demo.html">Interactive example</a></p></div>
<p id="copy-status" role="status" aria-live="polite"></p>${blocks}
</main><script>document.querySelectorAll('[data-copy]').forEach(button=>button.addEventListener('click',async()=>{const box=document.getElementById(button.dataset.copy);let copied=false;try{await navigator.clipboard.writeText(box.value);copied=true;}catch{box.focus();box.select();copied=document.execCommand('copy');}document.getElementById('copy-status').textContent=copied?'Complete code copied. Paste it into the matching Webflow field.':'Code selected. Press Ctrl+C or Command+C to copy.';}));</script></body></html>`);
